### ISSUE TITLE
getting 403 response for all resources

### ISSUE THREAD

**Issue by Swearengen** [adnanrahic/serverless-side-rendering-react-next#3]
I deployed forked app to aws without custom domains but getting 403 in console on all resources.

here is my serverless.yml

service: tenisliga-chat

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${self:custom.secrets.NODE_ENV}
  region: us-east-1
  environment:
    NODE_ENV: ${self:custom.secrets.NODE_ENV}

functions:
  server:
    handler: index.server
    events:
      - http: ANY /
      - http: ANY /{proxy+}

plugins:
  - serverless-apigw-binary

custom:
  secrets: ${file(secrets.json)}
  apigwBinary:
    types:
      - '*/*'

and here is [link](https://drive.google.com/file/d/1UeEGTMEqcvPfqfwHuQ8-eGMA9s0JjODR/view?usp=sharing) to screenshot of the console 

can anybody point me to right direction

**Comment by Vadorequest** [comment]
Using a custom domain may help fix this bug actually, because when deploying on AWS without custom domain, it adds the stage name at the end of the url and it causes issues.

**Comment by Swearengen** [comment]
Actually it helped, thx
